[helpers]

[desktop.files]
xinitrc = "~/.xinitrc"
zprofile = "~/.zprofile"

[bash]
depends = ["shell"]

[bash.files]
bashrc = "~/.bashrc"

[btop.files]
btop = "~/.config/btop/btop.conf"

[dwm.files]
"dwm/autostart.sh" = "~/.dwm/autostart.sh"

[doas.files]
doas = { target = "/etc/doas.conf", type = "template", owner = "root" }

[kitty.files]
kitty = "~/.config/kitty/kitty.conf"

[neofetch.files]
neofetch = "~/.config/neofetch/config.conf"

[nixos.files]
nixos = "~/.config/nixos/configuration.nix"

[nvim.files]
nvim = "~/.config/nvim/init.lua"

[obsidian.files]
obsidian = "~/.config/obsidian/Preferences"

[paru.files]
paru = "~/.config/paru/paru.conf"

[shell]
depends = ["desktop"]

[sudo.files]
sudoers = { target = "/etc/sudoers", type = "template", owner = "root" }

[shell.files]
aliasrc = "~/.aliasrc"
shellrc = "~/.shellrc"

[tmux.files]
tmux = "~/.tmux.conf"

[topgrade.files]
topgrade = "~/.config/topgrade.toml"

[zsh]
depends = ["shell"]

[zsh.files]
zshrc = "~/.zshrc"
