[helpers]

[desktop.files]
.xinitrc = "~/.xinitrc"
.zprofile = "~/.zprofile"

[bash]
depends = ["shell"]

[bash.files]
bashrc = "~/.bashrc"

[btop.files]
btop.conf = "~/.config/btop/btop.conf"

[dwm.files]
"dwm/autostart.sh" = "~/.dwm/autostart.sh"

[kitty.files]
kitty.conf = "~/.config/kitty/kitty.conf"

[neofetch.files]
neofetch.conf = "~/.config/neofetch/config.conf"

[nixos.files]
nixos.nix = "~/.config/nixos/configuration.nix"

[nvim.files]
nvim = "~/.config/nvim/init.lua"

[obsidian.files]
obsidian = "~/.config/obsidian/Preferences"

[paru.files]
paru.conf = "~/.config/paru/paru.conf"

[shell]
depends = ["desktop"]

[sudo.files]
sudoers = { target = "/etc/sudoers", type = "template", owner = "root" }

[shell.files]
aliasrc = "~/.aliasrc"
shellrc = "~/.shellrc"

[tmux.files]
tmux.conf = "~/.tmux.conf"

[topgrade.files]
topgrade.toml = "~/.config/topgrade.toml"

[zsh]
depends = ["shell"]

[zsh.files]
zshrc = "~/.zshrc"
