includes = []
packages = [
"btop", 
"dwm", 
"cargo",
"grub",
"neofetch", 
"nvim", 
"obsidian", 
"pacman",
"paru", 
"shell", 
"tmux", 
"topgrade", 
"zsh",
"desktop"]

[files]

[variables]
run = "sudo"
